### PR TITLE
ESON to support lists of enum

### PR DESCRIPTION
**Pull request by nbhusare**
Updated the proposal provider to show a list of enum literals

### CODE REVIEW

**Comment by vorburger** [comment]
@nbhusare look' good, well done.

The Commit shows up as from "unknown" (even though its from you) - this could may be a problem for future upcoming eclipse.org (planned) IP review.. is there any chance I could politely ask you to fix that?

Test case covering this would be great too - any chance for that? Thanks!

**Comment by nbhusare** [comment]
Setting the global username did the trick. Only new commits have the username set, old commits will still show unknown.

**Comment by nbhusare** [comment]
Experiencing a strange behavior - On content assist, I don't see the  "enumListTestContainer". Please see attached SS. 
Any idea what might be wrong ? I need the above for my test.

**Comment by nbhusare** [comment]
Updated the ecore/genmodel.
Pushed test - com.googlecode.efactory.ui.contentassist.tests.EnumListProposalProviderTest

**Comment by nbhusare** [comment]
@vorburger - The [test](https://github.com/nbhusare/efactory/blob/b976ff94a77002891531575a93a983eea036060a/com.googlecode.efactory.tests/src/com/googlecode/efactory/ui/contentassist/tests/EnumListProposalProviderTest.java) for content assist doesn't seem to work. Do you mind reviewing the same.

**Comment by vorburger** [comment]
Closing this very old Pull Request I had totally forgotten about, because this repo is no longer actively maintained; ESON is now an eclipse.org EMF sub-project; see https://wiki.eclipse.org/ESON. Contributions there are more than welcome (I don't actively work on it anymore myself, but I do occasionally review and merge anything proposed by contributors.)

**Pull request closed without merging**
